#!/usr/bin/env ruby

require_relative '../init'

require 'event_source/event_store/http/controls'

ip_address = ENV['IP_ADDRESS'] || '127.0.0.1'
ext_http_port = Integer(ENV['PORT'] || EventSource::EventStore::HTTP::Controls::Port.example)
int_http_port = ext_http_port - 1
cluster_size = Integer(ENV['CLUSTER_SIZE'] || '1')

logger = Log.get __FILE__

logger.info "Starting EventStore (IP: #{ip_address}, ClusterSize: #{cluster_size}, Port: #{ext_http_port})"

command = %W(
  ./run-node.sh
  --run-projections=System
  --mem-db
  --ext-ip=#{ip_address}
  --int-ip=#{ip_address}
)

if cluster_size > 1
  command << "--cluster-size=#{cluster_size}"
  command << "--gossip-seed=127.0.111.1:#{int_http_port}"
  command << "--discover-via-dns=false"
end

logger.info "Command: #{command * ' '}"

Dir.chdir 'event-store' do
  exec *command
end
